# Generated by Django 4.0.5 on 2022-06-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=255),
        ),
    ]
