# Generated by Django 4.0.5 on 2022-06-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_aboutsection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default=True, max_length=255),
        ),
    ]
