# Generated by Django 4.0.5 on 2022-06-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderName', models.CharField(max_length=255)),
                ('SenderEmail', models.CharField(max_length=255)),
                ('SenderSubject', models.CharField(max_length=255)),
                ('SenderContent', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
