version: "3.1"

services:
  postgres:
    image: postgres
    volumes:
      - ./pgdb/:/var/lib/postgressql/data 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres